import type { Metadata } from 'next';
import { Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { HamburgerMenu } from '@/components/shared/menu';

const paperlogy = localFont({
  variable: '--font-paperlogy',
  display: 'swap',
  src: [
    { path: './fonts/Paperlogy-4Regular.woff2', weight: '400', style: 'normal' },
    { path: './fonts/Paperlogy-5Medium.woff2', weight: '500', style: 'normal' },
    { path: './fonts/Paperlogy-6SemiBold.woff2', weight: '600', style: 'normal' },
  ],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${paperlogy.variable} ${geistMono.variable} antialiased`}
    >
      <body className='min-h-screen bg-[#f3f3f3] flex items-center justify-center px-6'>
        <main className='relative w-full max-w-310 h-180 rounded-[32px] bg-[#dbe7d8] overflow-hidden'>
          <HamburgerMenu />
          {children}
        </main>
      </body>
    </html>
  );
}
