import { LoginButton } from '@/components/shared/buttons';
import { UserNickname } from '@/components/shared/user-nickname';
import { Toaster } from '@/components/ui/sonner';
import { TooltipProvider } from '@/components/ui/tooltip';
import { getMyProfile } from '@/lib/api/users';
import type { Metadata } from 'next';
import { Geist_Mono, Nanum_Pen_Script } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const paperlogy = localFont({
  variable: '--font-paperlogy',
  display: 'swap',
  src: [
    {
      path: './fonts/Paperlogy-4Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    { path: './fonts/Paperlogy-5Medium.woff2', weight: '500', style: 'normal' },
    {
      path: './fonts/Paperlogy-6SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const nanumPen = Nanum_Pen_Script({
  variable: '--font-nanum-pen',
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 로그아웃 상태에선 401 로 throw 되므로 catch 로 null 폴백.
  const profile = await getMyProfile().catch(() => null);

  return (
    <html
      lang='en'
      className={`${paperlogy.variable} ${geistMono.variable} ${nanumPen.variable} antialiased`}
    >
      <body className='min-h-dvh bg-[#dbe7d8] md:flex md:items-center md:justify-center md:bg-[#f3f3f3] md:px-6'>
        <TooltipProvider delay={200}>
          <main className='relative min-h-dvh w-full overflow-hidden bg-[#dbe7d8] md:h-180 md:min-h-0 md:max-w-310 md:rounded-[32px]'>
            <div className='flex flex-col items-end justify-end gap-3 p-4'>
              <UserNickname nickname={profile?.nickname} />
              <LoginButton />
            </div>
            {children}
          </main>
        </TooltipProvider>
        <Toaster position='top-center' />
      </body>
    </html>
  );
}
